# Generated by Django 4.1.5 on 2023-01-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_login_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='feedback',
        ),
        migrations.RenameModel(
            old_name='login',
            new_name='user',
        ),
    ]
