# Generated by Django 4.1.5 on 2023-01-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_home_feedback_rename_login_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='home',
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='login',
        ),
    ]
