# Generated by Django 4.1.5 on 2023-01-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckc', models.CharField(max_length=30)),
                ('truckt', models.CharField(max_length=30)),
                ('truckn', models.CharField(max_length=30)),
            ],
        ),
    ]
