# Generated by Django 4.1.5 on 2023-01-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_driver_cardn_alter_driver_cnic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckc', models.CharField(max_length=30)),
                ('truckt', models.CharField(max_length=30)),
                ('truckn', models.CharField(max_length=30)),
            ],
        ),
    ]
